---
- name: ssh configuration management
  hosts: webservers
  remote_user: vagrant
  become: yes

  tasks:          
    
    - name: Change SSH daemon configuration
      lineinfile:
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        path: /etc/ssh/sshd_config
      
      loop:
        - line: 'AddressFamily inet'
          regexp: '^(#)?AddressFamily'
                    
        - line: 'PermitRootLogin no'
          regexp: '^(#)?PermitRootLogin'
          
        - line: 'MaxAuthTries 3'
          regexp: '^(#)?MaxAuthTries'
          
        - line: 'HostbasedAuthentication no'
          regexp: '^(#)?HostbasedAuthentication'  
          
        - line: 'IgnoreRhosts no'
          regexp: '^(#)?IgnoreRhosts'
          
        - line: 'PermitEmptyPasswords no'
          regexp: '^(#)?PermitEmptyPasswords'
          
        - line: 'PasswordAuthentication no'
          regexp: '^(#)?PasswordAuthentication'
          
        - line: 'X11Forwarding no'
          regexp: '^(#)?X11Forwarding'
            
        - line: 'ClientAliveInterval 900'
          regexp: '^(#)?ClientAliveInterval'
          
        - line: 'ClientAliveCountMax 0'
          regexp: '^(#)?ClientAliveCountMax'
            
        - line: 'Banner /etc/issue.net'
          regexp: '^(#)?Banner'
    
    - name: Update banner message
      copy:
        dest: /etc/issue.net
        content: |
          #################################################################
          *                                                               #
          * This system is for the use of authorized users only.          #
          * Usage of this system monitored & recorded by system personnel.#
          *                                                               #
          #################################################################
        owner: root
        group: root
        mode: '0744'   

    
    - name: Restart SSHD service
      ansible.builtin.systemd:
        name: sshd
        state: restarted

